function setup_final_parking_test(save_model)
%SETUP_FINAL_PARKING_TEST Configure Day4_5 for the final-project parking lot.
%
% Run this from MATLAB while CarMaker for Simulink is available:
%   cd <Practice_sample>/src_cm4sl/Models/Day4_5
%   setup_final_parking_test
%
% The script:
%   1. backs up Day4_5_Scenario_1.slx,
%   2. writes final-project parking constants into the Day4_5 model,
%   3. maps the seven Day4_5 obstacle readers to nearby final parking cars,
%   4. creates Data/TestRun/day4_5_final_parking_only from day7_final.

if nargin < 1
    save_model = true;
end

model = 'Day4_5_Scenario_1';
model_dir = fileparts(mfilename('fullpath'));
project_dir = fullfile(model_dir, '..', '..', '..');
test_run_dir = fullfile(project_dir, 'Data', 'TestRun');

slx_file = fullfile(model_dir, [model '.slx']);
if bdIsLoaded(model) && strcmp(get_param(model, 'Dirty'), 'on')
    error(['%s already has unsaved in-memory changes.\n' ...
        'To keep them, run:    save_system(''%s'')\n' ...
        'To discard them, run: close_system(''%s'', 0)\n' ...
        'Then rerun setup_final_parking_test.'], model, model, model);
end

if save_model
    backup_file = fullfile(model_dir, ...
        sprintf('%s_backup_before_final_parking_%s.slx', model, datestr(now, 'yyyymmdd_HHMMSS')));
    copyfile(slx_file, backup_file);
    fprintf('Backed up model: %s\n', backup_file);
end

if ~bdIsLoaded(model)
    load_system(slx_file);
end

% Final-project parking-only target.
% Handoff point from the lane-following / waypoint logic: the waypoints break at
% Lane 5's last GLOBAL coordinate (1.81922874699780, -36.6414715196313) and the
% vehicle stops there; parking takes over from this pose (per team handoff, FP).
% NOTE: heading at handoff is not yet available from the upstream logic; 180 deg
% (nose-to-west) was the prior tested value but is geometrically infeasible at
% x=1.82 (car body / back-out corridor would run off the x=0 grid edge). The
% offline yaw sweep (run_newstart_yawsweep.m) picks the solvable heading; update
% start_yaw_deg below to the real value once the lane logic can provide it.
start_xyz = [1.81922874699780, -36.6414715196313, 2.5];
start_yaw_deg = 180.0;   % PROVISIONAL — set from yaw-sweep result / real handoff
start_xy = start_xyz(1:2);
goal_xy = [17.0, -7.0];
goal_yaw = '-pi/2';

% Boundary corners of the final parking lot area. The entrance road/link runs
% roughly from [4.0 -36.6] to [47.6 -36.6]. The drivable polygon's west edge is
% extended from x=4.0 to x=0.0 so the new handoff start (x=1.82) falls INSIDE
% the drivable region (cells outside the polygon are marked occupied, so the
% start would otherwise be in an obstacle). The occupancy grid itself is fixed
% at x in [0,100], y in [-100,0] (generate_map_ map_const_local), so x_min=0.0
% is the grid's west edge and the maximum we can extend to.
map_boundary = [
    0.0,  -4.0
    0.0, -46.8
   48.0,  -4.0
   48.0, -46.8
];

% Final-project traffic cars are IPG CompanyCar objects.
traffic_width = 1.97;
traffic_length = 4.47;

% Day4_5 add_obstacle_ now uses all final-project static parked cars.
obstacle_ids = 0:20;

% Start point.
set_const(model, 3, start_xy(1));      % Constant2: Start_Point x
set_const(model, 4, start_xy(2));      % Constant3: Start_Point y

% Finish point.
set_const(model, 5, goal_xy(1));       % Constant4: Finish_Point x
set_const(model, 6, goal_xy(2));       % Constant5: Finish_Point y
set_const_text(model, 4009, goal_yaw); % Constant15: goal_yaw

% Map boundary.
set_const(model, 7,    map_boundary(1, 1));
set_const(model, 9,    map_boundary(1, 2));
set_const(model, 8,    map_boundary(2, 1));
set_const(model, 10,   map_boundary(2, 2));
set_const(model, 3775, map_boundary(3, 1));
set_const(model, 3776, map_boundary(3, 2));
set_const(model, 3778, map_boundary(4, 1));
set_const(model, 3779, map_boundary(4, 2));

% Obstacle vehicle size: [width; length].
set_const(model, 2, traffic_width);    % Constant10
set_const(model, 1, traffic_length);   % Constant1

% Day4_5 Traffic Object subsystem. These SIDs are generated by
% expand_final_parking_obstacle_readers.m / the patched final-parking model.
traffic_object_sids = 5200:5220;
traffic_id_const_sids = 5100:5120;
for k = 1:numel(obstacle_ids)
    traffic_name = sprintf('T%02d', obstacle_ids(k));
    set_param(sid_handle(model, traffic_object_sids(k)), 'xname', traffic_name);
    set_const(model, traffic_id_const_sids(k), obstacle_ids(k));
end

if save_model
    save_system(model);
    fprintf('Saved model: %s\n', slx_file);
else
    fprintf('Model updated in memory only. Call save_system(''%s'') to save.\n', model);
end

test_run_out = write_final_parking_test_run(test_run_dir, start_xyz, start_yaw_deg);
fprintf('Created test run: %s\n', test_run_out);

fprintf('\nFinal parking setup complete.\n');
fprintf('  Start       : [%.1f %.1f]\n', start_xy(1), start_xy(2));
fprintf('  Goal        : [%.1f %.1f], yaw = %s rad\n', goal_xy(1), goal_xy(2), goal_yaw);
fprintf('  Obstacles   : %s\n', sprintf('T%02d ', obstacle_ids));
fprintf('  TestRun     : day4_5_final_parking_only\n');
fprintf('  Road        : day7_final.rd5\n\n');

end

function h = sid_handle(model, sid)
h = Simulink.ID.getHandle(sprintf('%s:%d', model, sid));
if isempty(h) || h == -1
    error('Could not resolve Simulink SID %s:%d.', model, sid);
end
end

function set_const(model, sid, value)
set_const_text(model, sid, sprintf('%.15g', value));
end

function set_const_text(model, sid, value)
set_param(sid_handle(model, sid), 'Value', value);
end

function test_run_out = write_final_parking_test_run(test_run_dir, start_xyz, start_yaw_deg)
src = fullfile(test_run_dir, 'day7_final');
test_run_out = fullfile(test_run_dir, 'day4_5_final_parking_only');

txt = fileread(src);

txt = replace_line(txt, 'Road.FName', 'Road.FName = day7_final.rd5');
txt = replace_line(txt, 'Vehicle.Routing.Type', 'Vehicle.Routing.Type = Route');
txt = replace_line(txt, 'Vehicle.Routing.ObjId', 'Vehicle.Routing.ObjId = 85');
txt = replace_line(txt, 'Vehicle.StartPos.Type', 'Vehicle.StartPos.Type = Global');
txt = replace_line(txt, 'Vehicle.StartPos.ObjId', 'Vehicle.StartPos.ObjId = 85');
txt = replace_line(txt, 'Vehicle.StartPos', sprintf('Vehicle.StartPos = %.3f %.3f %.3f', ...
    start_xyz(1), start_xyz(2), start_xyz(3)));
txt = replace_line(txt, 'Vehicle.StartPos.Orientation.Type', ...
    'Vehicle.StartPos.Orientation.Type = Relative');
txt = replace_line(txt, 'Vehicle.StartPos.Orientation', ...
    sprintf('Vehicle.StartPos.Orientation = 0.0 0.0 %.3f', start_yaw_deg));
txt = replace_line(txt, 'DrivMan.Man.Start.Velocity', ...
    'DrivMan.Man.Start.Velocity = 0.0');
txt = replace_line(txt, 'DrivMan.Man.Start.LaneOffset', ...
    'DrivMan.Man.Start.LaneOffset = 0');

% Keep static parked cars T00..T20 and ignore the moving-route traffic T21..T28.
txt = replace_line(txt, 'Traffic.N', 'Traffic.N = 21');

fid = fopen(test_run_out, 'w');
if fid < 0
    error('Could not write test run: %s', test_run_out);
end
cleanup = onCleanup(@() fclose(fid));
fwrite(fid, txt);
end

function txt = replace_line(txt, key, new_line)
% MATLAB regexp's dot can span newlines, so avoid .* here. Otherwise the
% first replacement can accidentally consume the rest of a CarMaker file.
pattern = ['(?m)^' regexptranslate('escape', key) '\s*=[^\r\n]*'];
if isempty(regexp(txt, pattern, 'once'))
    error('Could not find key in TestRun: %s', key);
end
txt = regexprep(txt, pattern, new_line, 'once');
end
